stages:
  - test

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo

cache:
  paths:
    - cargo/
    - target/

.wasm32-unknown-unknown: &wasm32-unknown-unknown
  stage: test
  before_script:
    - rustc --version
    - rustup target add wasm32-unknown-unknown
    - apt update -y
    - apt install -y libssl-dev pkg-config nodejs
    - cargo install wasm-bindgen-cli --target x86_64-unknown-linux-gnu
  script:
    - cargo test --verbose

stable-wasm32-unknown-unknown:
  image: amd64/rust:slim-buster
  <<: *wasm32-unknown-unknown

nightly-wasm32-unknown-unknown:
  image: rustlang/rust:nightly-buster-slim
  <<: *wasm32-unknown-unknown
