stages:
  - test

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo

cache:
  paths:
    - cargo/
    - target/

stable-wasm32-unknown-unknown:
  stage: test
  image: amd64/rust:slim-buster
  before_script:
    - rustc --version
    - rustup target add wasm32-unknown-unknown
    - apt update -y
    - apt install -y libssl-dev pkg-config
    - cargo install wasm-bindgen-cli
  script:
    - cargo test --verbose
